Updated an access modifier of an object decleration in Sandbox.java
robolectric/robolectric pull request #7880
Opened 2022-12-21 12:53 UTC by sandeshShahapur

### Overview
I spotted a todo comment that specified to not have the access specifier of the object `classHandler` (declaration) in line 23 as `public`. Therefore I resolved it by changing the access modifier to `private`. I hope this is valid (I'm new), thank you!

### Proposed Changes
```diff
- public ClassHandler classHandler; // todo not public
+ private ClassHandler classHandler; // todo not public
```

2022-12-21 13:29 UTC, utzcoz requested changes

2022-12-21 13:29 UTC, utzcoz commented on sandbox/src/main/java/org/robolectric/internal/bytecode/Sandbox.java
> +  private ClassHandler classHandler; // todo not public
Remove this todo comment too?

2022-12-21 13:50 UTC, utzcoz commented
@sandeshShahapur Please squash your commits to one.

2022-12-21 14:04 UTC, sandeshShahapur commented
> @sandeshShahapur Please squash your commits to one.

@utzcoz  can you please guide me on how to do that?

2022-12-21 14:13 UTC, utzcoz commented
> > @sandeshShahapur Please squash your commits to one.
> 
> @utzcoz can you please guide me on how to do that?

There are many tutorials on the internet: e.g. https://www.git-tower.com/learn/git/faq/git-squash/.

2023-01-21 05:32 UTC, utzcoz commented
@sandeshShahapur You need to rebase on the latest master with only one commit.

2023-03-11 12:49 UTC, utzcoz commented
Hi @sandeshShahapur , after long time no-response, I will close this PR. Feel free to reopen it if you want to continue this PR. Thanks.

2023-03-11 12:49 UTC, closed without merging