Fix typo of addExtensionMimeTypeMapping
robolectric/robolectric pull request #8341
Opened 2023-07-04 01:03 UTC by tonionagauzzi

### Overview
Fix typo of `addExtensionMimeTypeMapping`

### Proposed Changes
I found `addExtensionMimeTypeMapping` incorrectly coded as `addExtensionMimeTypMapping`. Therefore, I propose this correction.

2023-07-04 05:53 UTC, utzcoz commented
I only found Chromium is using this API: https://github.com/search?q=addExtensionMimeTypMapping&type=code.

2023-07-04 05:56 UTC, utzcoz commented
@tonionagauzzi You need to add commit body for your commit.
> Error: The commit message should have a descriptive body
Error: Process completed with exit code 1.

2023-07-04 21:44 UTC, hoisie approved these changes

2023-07-05 03:05 UTC, utzcoz requested changes
@tonionagauzzi Please update your commit message, and I think we can merge it after that.

2023-07-05 11:41 UTC, utzcoz approved these changes
LGTM.

2023-07-05 12:05 UTC, merged

2023-07-05 12:05 UTC, utzcoz commented
@tonionagauzzi Thanks for your contribution. And congratulations to your first Robolectric contribution.